import type { CardDef } from './types';

/**
 * Cartes originales ATLAS ROYALE.
 *
 * Ajouter une carte = ajouter un objet ici. Rien d'autre à modifier :
 * `effect` est de la donnée, interprétée par `applyEffect()` dans engine.ts,
 * et `art` + `tone` pilotent le rendu 3D de la carte.
 */
export const CARDS: CardDef[] = [
  /* ---------------- DESTIN — évènements mondiaux, déplacements, chaos ---- */
  { id: 'd_alizes', deck: 'destin', rarity: 'commune', tone: 'positif', art: 'wind',
    title: 'Vents Alizés', text: 'Les courants vous portent. Avancez de 3 cases.',
    effect: { k: 'moveBy', steps: 3 } },
  { id: 'd_escale', deck: 'destin', rarity: 'commune', tone: 'neutre', art: 'plane',
    title: 'Escale Imprévue', text: 'Rejoignez le hub le plus proche.',
    effect: { k: 'moveToNearest', target: 'hub' } },
  { id: 'd_rappel', deck: 'destin', rarity: 'commune', tone: 'positif', art: 'compass',
    title: 'Rappel au Siège', text: 'Retournez au Départ et encaissez la prime.',
    effect: { k: 'moveTo', tile: 0, collectGo: true } },
  { id: 'd_tempete', deck: 'destin', rarity: 'commune', tone: 'negatif', art: 'storm',
    title: 'Tempête Tropicale', text: 'Vos vols sont cloués au sol. Reculez de 4 cases.',
    effect: { k: 'moveBy', steps: -4 } },
  { id: 'd_controle', deck: 'destin', rarity: 'commune', tone: 'negatif', art: 'siren',
    title: 'Contrôle Fiscal', text: 'Direction la Prison. Sans passer par le Départ.',
    effect: { k: 'goToJail' } },
  { id: 'd_immunite', deck: 'destin', rarity: 'rare', tone: 'positif', art: 'key',
    title: 'Immunité Diplomatique', text: 'Conservez cette carte : elle ouvre les portes de la Prison.',
    effect: { k: 'jailFree' } },
  { id: 'd_sommet', deck: 'destin', rarity: 'commune', tone: 'positif', art: 'globe',
    title: 'Sommet Mondial', text: 'Votre présence est courtisée. Chaque joueur vous verse 300 €.',
    effect: { k: 'collectFromEach', amount: 300 } },
  { id: 'd_banquet', deck: 'destin', rarity: 'commune', tone: 'negatif', art: 'glass',
    title: 'Banquet d’Honneur', text: 'L’addition est pour vous : 250 € à chaque joueur.',
    effect: { k: 'payEach', amount: 250 } },
  { id: 'd_orbital', deck: 'destin', rarity: 'commune', tone: 'neutre', art: 'satellite',
    title: 'Fenêtre Orbitale', text: 'Rejoignez le réseau le plus proche.',
    effect: { k: 'moveToNearest', target: 'reseau' } },
  { id: 'd_monaco', deck: 'destin', rarity: 'rare', tone: 'neutre', art: 'yacht',
    title: 'Invitation à Monaco', text: 'Rendez-vous à Monaco, quel qu’en soit le prix.',
    effect: { k: 'moveTo', tile: 39, collectGo: true } },
  { id: 'd_tokyo', deck: 'destin', rarity: 'commune', tone: 'neutre', art: 'neon',
    title: 'Nuit à Tokyo', text: 'Rejoignez Tokyo.',
    effect: { k: 'moveTo', tile: 31, collectGo: true } },
  { id: 'd_sahara', deck: 'destin', rarity: 'commune', tone: 'neutre', art: 'dune',
    title: 'Traversée du Sahara', text: 'Rejoignez Marrakech.',
    effect: { k: 'moveTo', tile: 1, collectGo: true } },
  { id: 'd_amende', deck: 'destin', rarity: 'commune', tone: 'negatif', art: 'siren',
    title: 'Amende de Survol', text: 'Versez 400 € à la cagnotte du Parc.',
    effect: { k: 'cashToPot', amount: 400 } },
  { id: 'd_mecene', deck: 'destin', rarity: 'commune', tone: 'positif', art: 'trophy',
    title: 'Mécène Anonyme', text: 'Un admirateur vous adresse 800 €.',
    effect: { k: 'cash', amount: 800 } },
  { id: 'd_greve', deck: 'destin', rarity: 'commune', tone: 'negatif', art: 'siren',
    title: 'Grève des Douanes', text: 'Vos marchandises dorment au port. Payez 600 € à la cagnotte.',
    effect: { k: 'cashToPot', amount: 600 } },
  { id: 'd_aurore', deck: 'destin', rarity: 'rare', tone: 'positif', art: 'aurora',
    title: 'Aurore Boréale', text: 'Un spectacle rare, un contrat rare : 1 500 €.',
    effect: { k: 'cash', amount: 1500 } },
  { id: 'd_seisme', deck: 'destin', rarity: 'rare', tone: 'negatif', art: 'crack',
    title: 'Secousse Sismique', text: 'Mise aux normes : 400 € par maison, 700 € par villa, 1 200 € par hôtel.',
    effect: { k: 'repairs', perHouse: 400, perVilla: 700, perHotel: 1200 } },
  { id: 'd_jackpot', deck: 'destin', rarity: 'legendaire', tone: 'positif', art: 'jackpot',
    title: 'Coup du Sort', text: 'La cagnotte du Parc vous revient intégralement.',
    effect: { k: 'takePot' } },
  { id: 'd_exil', deck: 'destin', rarity: 'rare', tone: 'chaos', art: 'siren',
    title: 'Exil Doré', text: 'Prison — mais la banque vous verse 1 000 € de dédommagement.',
    effect: { k: 'multi', effects: [{ k: 'cash', amount: 1000 }, { k: 'goToJail' }] } },
  { id: 'd_retour', deck: 'destin', rarity: 'commune', tone: 'positif', art: 'compass',
    title: 'Vol de Nuit', text: 'Avancez de 6 cases.',
    effect: { k: 'moveBy', steps: 6 } },
  { id: 'd_dubai', deck: 'destin', rarity: 'commune', tone: 'neutre', art: 'dune',
    title: 'Convocation à Dubaï', text: 'Rejoignez Dubaï.',
    effect: { k: 'moveTo', tile: 37, collectGo: true } },
  { id: 'd_visa', deck: 'destin', rarity: 'commune', tone: 'negatif', art: 'stamp',
    title: 'Visa Refusé', text: 'Reculez de 2 cases et payez 200 € à la cagnotte.',
    effect: { k: 'multi', effects: [{ k: 'moveBy', steps: -2 }, { k: 'cashToPot', amount: 200 }] } },
  { id: 'd_parade', deck: 'destin', rarity: 'rare', tone: 'positif', art: 'trophy',
    title: 'Parade Triomphale', text: 'Chaque joueur vous honore de 500 €.',
    effect: { k: 'collectFromEach', amount: 500 } },
  { id: 'd_eclipse', deck: 'destin', rarity: 'legendaire', tone: 'chaos', art: 'eclipse',
    title: 'Éclipse Totale', text: 'Le monde retient son souffle. Avancez de 10 cases.',
    effect: { k: 'moveBy', steps: 10 } },
  { id: 'd_liberte', deck: 'destin', rarity: 'rare', tone: 'positif', art: 'key',
    title: 'Laissez-Passer', text: 'Gardez cette carte pour sortir de Prison.',
    effect: { k: 'jailFree' } },

  /* ---------------- MARCHÉ — économie, immobilier, patrimoine ----------- */
  { id: 'm_dividende', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'chart',
    title: 'Dividende Trimestriel', text: 'Vos titres rapportent 600 €.',
    effect: { k: 'cash', amount: 600 } },
  { id: 'm_krach', deck: 'marche', rarity: 'rare', tone: 'negatif', art: 'crash',
    title: 'Krach Éclair', text: 'Les marchés dévissent. Versez 1 200 € à la cagnotte.',
    effect: { k: 'cashToPot', amount: 1200 } },
  { id: 'm_loyers', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'building',
    title: 'Indexation des Loyers', text: 'Encaissez 250 € par propriété détenue.',
    effect: { k: 'cashPerProperty', amount: 250 } },
  { id: 'm_taxe', deck: 'marche', rarity: 'commune', tone: 'negatif', art: 'receipt',
    title: 'Taxe Foncière', text: 'Payez 200 € par propriété détenue.',
    effect: { k: 'cashPerProperty', amount: -200 } },
  { id: 'm_negoce', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'handshake',
    title: 'Négoce Habile', text: '20 % de remise sur votre prochaine acquisition.',
    effect: { k: 'discountNextPurchase', percent: 20 } },
  { id: 'm_enchere', deck: 'marche', rarity: 'rare', tone: 'positif', art: 'hammer',
    title: 'Enchère Remportée', text: '35 % de remise sur votre prochaine acquisition.',
    effect: { k: 'discountNextPurchase', percent: 35 } },
  { id: 'm_renovation', deck: 'marche', rarity: 'commune', tone: 'negatif', art: 'crane',
    title: 'Ravalement Obligatoire', text: '250 € par maison, 500 € par villa, 900 € par hôtel.',
    effect: { k: 'repairs', perHouse: 250, perVilla: 500, perHotel: 900 } },
  { id: 'm_fonds', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'vault',
    title: 'Fonds Souverain', text: 'Une entrée au capital : 1 000 €.',
    effect: { k: 'cash', amount: 1000 } },
  { id: 'm_audit', deck: 'marche', rarity: 'commune', tone: 'negatif', art: 'receipt',
    title: 'Audit Surprise', text: 'Honoraires du cabinet : 500 € à la cagnotte.',
    effect: { k: 'cashToPot', amount: 500 } },
  { id: 'm_ipo', deck: 'marche', rarity: 'rare', tone: 'positif', art: 'chart',
    title: 'Introduction en Bourse', text: 'Le marché s’arrache vos titres : 2 000 €.',
    effect: { k: 'cash', amount: 2000 } },
  { id: 'm_rachat', deck: 'marche', rarity: 'rare', tone: 'negatif', art: 'crash',
    title: 'Rachat Hostile', text: 'Vous rachetez vos parts : 400 € à chaque joueur.',
    effect: { k: 'payEach', amount: 400 } },
  { id: 'm_permis', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'crane',
    title: 'Permis de Construire', text: 'Subvention à la construction : 900 €.',
    effect: { k: 'cash', amount: 900 } },
  { id: 'm_change', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'coins',
    title: 'Effet de Change', text: 'La devise joue en votre faveur : 450 €.',
    effect: { k: 'cash', amount: 450 } },
  { id: 'm_defaut', deck: 'marche', rarity: 'commune', tone: 'negatif', art: 'receipt',
    title: 'Défaut de Paiement', text: 'Un locataire s’évapore. 350 € à la cagnotte.',
    effect: { k: 'cashToPot', amount: 350 } },
  { id: 'm_monopole', deck: 'marche', rarity: 'legendaire', tone: 'positif', art: 'crown',
    title: 'Position Dominante', text: 'Chaque joueur vous verse 700 €.',
    effect: { k: 'collectFromEach', amount: 700 } },
  { id: 'm_saisie', deck: 'marche', rarity: 'legendaire', tone: 'chaos', art: 'vault',
    title: 'Saisie Conservatoire', text: 'La cagnotte est gelée à votre profit : elle vous revient.',
    effect: { k: 'takePot' } },
  { id: 'm_obligations', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'coins',
    title: 'Obligations Arrivées à Terme', text: 'Encaissez 750 €.',
    effect: { k: 'cash', amount: 750 } },
  { id: 'm_assurance', deck: 'marche', rarity: 'commune', tone: 'negatif', art: 'receipt',
    title: 'Prime d’Assurance', text: 'Renouvellement du contrat : 450 € à la cagnotte.',
    effect: { k: 'cashToPot', amount: 450 } },
  { id: 'm_expansion', deck: 'marche', rarity: 'rare', tone: 'positif', art: 'building',
    title: 'Plan d’Expansion', text: '400 € par propriété détenue.',
    effect: { k: 'cashPerProperty', amount: 400 } },
  { id: 'm_inspection', deck: 'marche', rarity: 'commune', tone: 'neutre', art: 'stamp',
    title: 'Inspection du Patrimoine', text: 'Rejoignez le Départ pour régulariser. Prime encaissée.',
    effect: { k: 'moveTo', tile: 0, collectGo: true } },
  { id: 'm_delit', deck: 'marche', rarity: 'rare', tone: 'negatif', art: 'siren',
    title: 'Délit d’Initié', text: 'La commission vous envoie en Prison.',
    effect: { k: 'goToJail' } },
  { id: 'm_heritage', deck: 'marche', rarity: 'rare', tone: 'positif', art: 'crown',
    title: 'Héritage Inattendu', text: 'Une succession lointaine vous lègue 1 800 €.',
    effect: { k: 'cash', amount: 1800 } },
  { id: 'm_liquidite', deck: 'marche', rarity: 'commune', tone: 'negatif', art: 'crash',
    title: 'Tension de Trésorerie', text: '300 € à chaque joueur.',
    effect: { k: 'payEach', amount: 300 } },
  { id: 'm_partenariat', deck: 'marche', rarity: 'commune', tone: 'positif', art: 'handshake',
    title: 'Partenariat Stratégique', text: 'Chaque joueur vous verse 200 €.',
    effect: { k: 'collectFromEach', amount: 200 } },
];

export const CARDS_BY_ID: Record<string, CardDef> = Object.fromEntries(
  CARDS.map((c) => [c.id, c]),
);

/** Les communes sont doublées : les cartes rares restent des évènements. */
export const deckWeights: Record<CardDef['rarity'], number> = {
  commune: 2, rare: 1, legendaire: 1,
};

export const buildDeck = (deck: CardDef['deck']): string[] =>
  CARDS.filter((c) => c.deck === deck).flatMap((c) =>
    Array.from({ length: deckWeights[c.rarity] }, () => c.id),
  );
